apiVersion: v1
kind: Service
metadata:
  name: php-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  # ‚±‚±‚É’Ç‰Á
spec:
  selector:
    app: php-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
